### ISSUE TITLE
Complete Application Systems page for 2021/22

### ISSUE THREAD

**Issue by cw118** [cw118/quetudesinfo#13]
The Application Systems page is nearly complete—updates and additional information should be finalized in the coming weeks for:

- [x] Done in #14 — Champlain College, Omnivox (the Lennoxville campus is under SRAM, the instructions for which are complete)
- [x] Done in #17 — Marianopolis College, Omnivox
- [x] Done in #17 — Any fixes, updates and improvements for previously completed application guides (+ links to official documents/guides)
