### ISSUE TITLE
Add a license, and issue and PR templates

### ISSUE THREAD

**Issue by cw118** [cw118/quetudesinfo#7]
Planned tasks:

- [x] #15 — Add/attribute licenses to QUÉtudes-info for clearer directives on sharing site content, and to "allow" contributions (open sourcing the project: two separate licenses for the content/prose and the code).
- [x] #22 — Update disclaimers and terms
- [x] #22 — issue and PR templates
- [x] #22 — Update "help" page entries, notably the "having issues" one
- [x] #15 — Replace current README with general overview, add various docs files for contributing, style guide, etc. (+ issue/PR/discussion/contributor etiquette)
- [x] #15 — Move current README content into `ABOUT.md` in a `docs` folder

The site footer should be updated to include a "contribute to QUÉtudes-info" banner, making it easier to locate the GitHub repo/source file (can be part of a PR/series of PRs fixing the other tasks in this issue or added and tracked separately).
